### ISSUE TITLE
[Win32] fails on '_file_time_now()'

### ISSUE THREAD

**Issue by gvanem** [PG1003/filesystem#1]
The `test/main.lua` works fine for the most part. But some times I get this error:
```
Running tests...
-- directory_iterator --
-- non_member_functions --
Not same; value 1: 'file_time_type.filesystem: 00000218DE98A668', value 2: 'file_time_type.filesystem: 00000218DE98A938'
stack traceback:
        ./test/tests/non_member_functions.lua:251: in function 'non_member_functions.file_time_now'
-- path --
-- directory_entry --
...tests completed
-- Test summary --
        Tests   Checks
Total:     70      204
Failed:     1        1
>>> tests failed!
```
A difference of 0x2D0 == 720 nano-sec? A feature of the NTFS cache?

I'm on Win-10 using Lua-5.4. And `filesystem.dll` was built with MSVC (VS-2022 Preview).
But using `clang-cl` (the MSVC compiler driver from LLVM), it crashes in `fs_read_symlink()`!

**Comment by PG1003** [comment]
I just noticed your issue that has opened almost 2 months ago, sorry for that.

To test Windows compatibility I used a Windows 10 VM (Virtual Box) on Linux (Manjaro). The sources and the Solution are in a directory in my Linux home directory which is shared with the VM.

I don't know which version of Visual Studio was used at the time the library was made public but running the tests again with Visual Studio 17.3.6 seems to have issues with symlinks as you already noticed.

I will try to debug the symlink issue on a non-VM Windows 10 and solve the the problem with file_time_now test.

**Comment by PG1003** [comment]
The issues I had with the symlink function is likely  caused by the mechanism to share the directory with sources between my Linux host and the Windows 10 VM. There were no issues on a non-VM Windows 10 machine.

I've found the cause of the crash when the filesystem module is built with clang-cl by Visual Studio.
The workaround is removing `noexcept` [on this line](https://github.com/PG1003/filesystem/blob/8889fd30bff394bc2acc4a05faea0a11603bd6d4/src/filesystem.cpp#L38).
I think this is an issue with Clang since the all exceptions are handled by a `catch( ... )` and no other C++ exception is thrown from the function. Maybe Clang is confused by long jumps that Lua uses to propagate errors.

The `file_time_now` test passed each time I ran the tests. The order in which the tests are executes is not deterministic and therefore hard to reproduce.
I have to do some more analyses.

**Comment by PG1003** [comment]
> A difference of 0x2D0 == 720 nano-sec? A feature of the NTFS cache?

The values printed by the failed test are object IDs / addresses, not values.

I think the issue the failing test is caused by the calculation of the time difference. The time difference is templated on a std::ratio for which the values of the numerator / denominator are platform defined.
The file system module converts the file time difference to seconds and is returned to the Lua world as a (floating point) number. At this point some accuracy may be lost and causes the test to fail.
I choose to convert the file time difference to seconds to avoid platform defined behavior in the Lua world.

There are two possibilities; accept the loss of accuracy and adapt the test with to tolerate an epsilon or create file time duration objects that behave like numbers. The latter may have performance impact since the duration object will be an user data object.

**Comment by PG1003** [comment]
I been thinking about it for some time and will probably go for the duration userdata solution.

**Comment by PG1003** [comment]
I just made a commit with the duration userdata solution.
For now I will wait for some time in case someone finds new related issues.
